title: Nawab Wasim Rahman
logo: /assets/img/headshot_circle.png
description: Educator; AL-ML;  Data Science; Analyst; ADVISOR at The Flexing Monks, Jorhat
#show_downloads: true
theme: jekyll-theme-timemachine
