title: Nawab Wasim Rahman
logo: /assets/img/headshot_circle.png
Description: Educator| AL-ML | Data Science | Analyst | ADVISOR at The Flexing Monks, Jorhat
Email: nawabwasimrahman@gmail.com
Phn no: 8473073955;
Address: Vill-Balibatgaon, Jelehuwagaon, Dist: Golaghat, Assam, Pin-785614
#show_downloads: true
theme: jekyll-theme-minimal
